`timescale 1ns/1ns

`include "../include/opcode.vh"
`include "../include/mem_path.vh"

// This testbench tests if the cpu module can decode and execute
// all the instructions specified in the spec (RV32I).
// Some tests for data hazards and control hazards are also included.

// How does the testbench work?
// For each test, the testbench initializes IMem with one or several instructions
// (encoded in binary format as specified in the spec) for testing.
// RegFile and DMem are also initialized with some data.
// Then, the clock is advanced until the cpu module gives correct result
// in the RegFile or DMem. If no correct result is returned after a "timeout" cycle,
// the testbench will be terminated (or failed)

// This setting is different from other testbenches, in which the BIOSMem or IMem is initialized
// with a hex file generated by compiling the assembly/C code of the corresponding
// test software (the hex file contains the binary encoding of the instructions and data
// of the program). Here, we manually generate the instructions and data.

// Don't just run the testbench, look at the tests, see what they do.
// The testbench is intended to provide you some examples to get started.
// Feel free to make your own change.
// Note that the testbench is by no means exhaustive.
// You should add your own tests if there are cases you think the testbench
// does not cover.
// The testbench does not cover reading from BIOS memory

//ONLY THESE INSTRCUTIONS WILL BE TESTED 
//R type: add, sub, or, and, xor, sll, srl 
//I type: addi,  ori, andi, xori, slli, srli, lw
//S type: sw
//B type: beq, bne
//J type: jal
//U type: lui

module cpu_tb();
    reg clk, rst;                          //TODO: ENSURE clk AND rst ARE SPELLED THE SAME
    parameter CPU_CLOCK_PERIOD = 20;

    reg [ 31:0] cycle;
    reg         done;
    reg [ 31:0] current_test_id = 0;
    reg [255:0] current_test_type;
    reg [ 31:0] current_output;
    reg [ 31:0] current_result;
    reg         all_tests_passed = 0;

    reg [  4:0] RD, RS1, RS2;
    reg [ 31:0] RD1, RD2;
    reg [  4:0] SHAMT;
    reg [ 31:0] IMM, IMM0, IMM1, IMM2, IMM3;
    reg [ 14:0] INST_ADDR;
    reg [ 14:0] DATA_ADDR;
    reg [ 14:0] DATA_ADDR0, DATA_ADDR1, DATA_ADDR2, DATA_ADDR3;
    reg [ 14:0] DATA_ADDR4, DATA_ADDR5, DATA_ADDR6, DATA_ADDR7;
    reg [ 14:0] DATA_ADDR8, DATA_ADDR9;
    reg [ 31:0] JUMP_ADDR;
    reg [ 31:0] BR_TAKEN_OP1  [5:0];
    reg [ 31:0] BR_TAKEN_OP2  [5:0];
    reg [ 31:0] BR_NTAKEN_OP1 [5:0];
    reg [ 31:0] BR_NTAKEN_OP2 [5:0];
    reg [  2:0] BR_TYPE       [5:0];
    reg [255:0] BR_NAME_TK1   [5:0];
    reg [255:0] BR_NAME_TK2   [5:0];
    reg [255:0] BR_NAME_NTK   [5:0];

    //CLK Generation
    initial clk = 0;
    always #(CPU_CLOCK_PERIOD/2) clk = ~clk;

    //TODO: Top module instantiation. CHANGE IF REQUIRED
    single_cycle cpu ( .clk (clk),
              .rst (rst) );

    wire [31:0] timeout_cycle = 10;

    //TODO: ENSURE REGISTERS OF REGFILE ARE NAMED AS'Registers' 
    //TODO: INSTRUCTION MEMORY IS NAMED AS 'memory'
    //TODO: DATA MEMORY IS NAMED AS 'memory' 
    //TODO: OTHERWISE CHANGE ALL OCCURENCES THROUGHOUT THE TESTBENCH
    //Reset IMem, DMem, and RegFile before running new test
    task reset;
        integer i;
        begin
        for (i = 0; i < 32; i = i + 1) begin
            `REGFILE_PATH.Registers[i] = 0;
        end
        for (i = 0; i < 512; i = i + 1) begin
            `DMEM_PATH.memory[i] = 0;
        end
        for (i = 0; i < 16; i = i + 1) begin
            `IMEM_PATH.memory[i] = 0;
        end
        end
    endtask

    task reset_cpu;
        @(posedge clk);
        rst = 1;
        #30;
        rst = 0;
    endtask

    task init_rf;
        begin
        for (int i = 1; i < 32; i = i + 1) begin
            `REGFILE_PATH.Registers[i] = 100 * i + 1;  
        end
        end
    endtask


    // Check for timeout
    // If a test does not return correct value in a given timeout cycle,
    // we terminate the testbench
    initial begin
        while (all_tests_passed === 0) begin
        @(posedge clk);

        if (cycle === timeout_cycle) begin
            $display("[Failed] Timeout at [%d] test %s, expected_result = %h, got = %h",
                    current_test_id, current_test_type, current_result, current_output);
            $finish();
        end

        end
    end

    always @(posedge clk) begin
        if (done === 0)
        cycle <= cycle + 1;
        else
        cycle <= 0;
    end

    // Check result of RegFile
    // If the write_back (destination) register has correct value (matches "result"), test passed
    // This is used to test instructions that update RegFile
    task check_result_rf;
        input [31:0]  rf_wa;
        input [31:0]  result;
        input [255:0] test_type;
        
        begin
            done = 0;
            current_test_id   = current_test_id + 1;
            current_test_type = test_type;
            current_result    = result;

            while (`REGFILE_PATH.Registers[rf_wa] !== result) begin     
                current_output = `REGFILE_PATH.Registers[rf_wa];
                @(negedge clk);
            end

            cycle = 0;
            done = 1;
            $display("[%d] Test %s passed!", current_test_id, test_type);
        end

    endtask

    // Check result of DMem
    // If the memory location of DMem has correct value (matches "result"), test passed
    // This is used to test store instructions
    task check_result_dmem;
        input [31:0]  addr;
        input [31:0]  result;
        input [255:0] test_type;

        begin
            done = 0;
            current_test_id   = current_test_id + 1;
            current_test_type = test_type;
            current_result    = result;

            while (`DMEM_PATH.memory[addr] !== result) begin   
                current_output = `DMEM_PATH.memory[addr];
                @(negedge clk);
            end

            cycle = 0;
            done = 1;
            $display("[%d] Test %s passed!", current_test_id, test_type);
        end

    endtask

    initial begin
        rst = 0;

        // Reset the CPU
        rst = 1;
        repeat (1) @(posedge clk);

        @(negedge clk);
        rst = 0;

        // Test R-Type Insts --------------------------------------------------
        // - ADD, SUB, SLL, XOR, OR, AND, SRL
        // Test few I-Type Insts --------------------------------------------------
        // - SLLI, SRLI, 
        RS1                          = 1; 
        RD1                          = -100;
        RS2                          = 2; 
        RD2                          =  200;
        RD                           = 3;
        `REGFILE_PATH.Registers[RS1] = RD1;
        `REGFILE_PATH.Registers[RS2] = RD2;
        SHAMT                        = 5'd20;
        INST_ADDR                    = 14'h0000;


        `IMEM_PATH.memory[INST_ADDR + 0]  = {`FNC7_0, RS2,   RS1, `FNC_ADD_SUB, 5'd3,  `OPC_ARI_RTYPE};
        `IMEM_PATH.memory[INST_ADDR + 1]  = {`FNC7_1, RS2,   RS1, `FNC_ADD_SUB, 5'd4,  `OPC_ARI_RTYPE};
        `IMEM_PATH.memory[INST_ADDR + 2]  = {`FNC7_0, RS2,   RS1, `FNC_SLL,     5'd5,  `OPC_ARI_RTYPE};
        `IMEM_PATH.memory[INST_ADDR + 3]  = {`FNC7_0, RS2,   RS1, `FNC_XOR,     5'd8,  `OPC_ARI_RTYPE};
        `IMEM_PATH.memory[INST_ADDR + 4]  = {`FNC7_0, RS2,   RS1, `FNC_OR,      5'd9,  `OPC_ARI_RTYPE};
        `IMEM_PATH.memory[INST_ADDR + 5]  = {`FNC7_0, RS2,   RS1, `FNC_AND,     5'd10, `OPC_ARI_RTYPE};
        `IMEM_PATH.memory[INST_ADDR + 6]  = {`FNC7_0, RS2,   RS1, `FNC_SRL_SRA, 5'd11, `OPC_ARI_RTYPE};
        `IMEM_PATH.memory[INST_ADDR + 7]  = {`FNC7_0, SHAMT, RS1, `FNC_SLL,     5'd13, `OPC_ARI_ITYPE};
        `IMEM_PATH.memory[INST_ADDR + 8]  = {`FNC7_0, SHAMT, RS1, `FNC_SRL_SRA, 5'd14, `OPC_ARI_ITYPE};

        reset_cpu();

        check_result_rf(5'd3,  32'h00000064, "R-Type ADD");
        check_result_rf(5'd4,  32'hfffffed4, "R-Type SUB");
        check_result_rf(5'd5,  32'hffff9c00, "R-Type SLL");
        check_result_rf(5'd8,  32'hffffff54, "R-Type XOR");
        check_result_rf(5'd9,  32'hffffffdc, "R-Type OR");
        check_result_rf(5'd10, 32'h00000088, "R-Type AND");
        check_result_rf(5'd11, 32'h00ffffff, "R-Type SRL");
        check_result_rf(5'd13, 32'hf9c00000, "R-Type SLLI");
        check_result_rf(5'd14, 32'h00000fff, "R-Type SRLI");

        // Test I-Type Insts --------------------------------------------------
        // - ADDI, XORI, ORI, ANDI
        // - LW
        // Test I-type arithmetic instructions

        reset();

        RS1                          = 1; 
        RD1                          = -100;
        `REGFILE_PATH.Registers[RS1] = RD1;
        IMM                          = -200;
        INST_ADDR                    = 14'h0000;

        `IMEM_PATH.memory[INST_ADDR + 0] = {IMM[11:0], RS1, `FNC_ADD_SUB, 5'd3, `OPC_ARI_ITYPE};
        `IMEM_PATH.memory[INST_ADDR + 3] = {IMM[11:0], RS1, `FNC_XOR,     5'd6, `OPC_ARI_ITYPE};
        `IMEM_PATH.memory[INST_ADDR + 4] = {IMM[11:0], RS1, `FNC_OR,      5'd7, `OPC_ARI_ITYPE};
        `IMEM_PATH.memory[INST_ADDR + 5] = {IMM[11:0], RS1, `FNC_AND,     5'd8, `OPC_ARI_ITYPE};
        
        reset_cpu();

        check_result_rf(5'd3,  32'hfffffed4, "I-Type ADD");
        check_result_rf(5'd6,  32'h000000a4, "I-Type XOR");
        check_result_rf(5'd7,  32'hffffffbc, "I-Type OR");
        check_result_rf(5'd8,  32'hffffff18, "I-Type AND");

        // Test I-type load instructions
        reset();

        `REGFILE_PATH.Registers[1]   = 32'h0000_0100;
        IMM0                         = 32'h0000_0000;
        INST_ADDR                    = 14'h0000;
        DATA_ADDR                    = (`REGFILE_PATH.Registers[1] + IMM0[11:0]);
        `DMEM_PATH.memory[DATA_ADDR>>2] = 32'hdeadbeef; // <----------------------------------------------- CHANGED

        `IMEM_PATH.memory[INST_ADDR + 0] = {IMM0[11:0], 5'd1, `FNC_LW,  5'd2,  `OPC_LOAD};
    
        reset_cpu();
        check_result_rf(5'd2,  32'hdeadbeef, "I-Type LW");


        // Test S-Type Insts --------------------------------------------------
        // - SW

        reset();

        `REGFILE_PATH.Registers[1]  = 32'h12345678;
        `REGFILE_PATH.Registers[2]  = 32'h0000_0010;

        IMM0 = 32'h0000_0100;
        INST_ADDR = 14'h0000;

        DATA_ADDR0 = (`REGFILE_PATH.Registers[2]  + IMM0[11:0]);
        DATA_ADDR1 = (`REGFILE_PATH.Registers[3]  + IMM0[11:0]);
        DATA_ADDR2 = (`REGFILE_PATH.Registers[4]  + IMM1[11:0]);
        DATA_ADDR3 = (`REGFILE_PATH.Registers[5]  + IMM2[11:0]);
        DATA_ADDR4 = (`REGFILE_PATH.Registers[6]  + IMM3[11:0]);

        DATA_ADDR5 = (`REGFILE_PATH.Registers[7]  + IMM0[11:0]);
        DATA_ADDR6 = (`REGFILE_PATH.Registers[8]  + IMM1[11:0]);
        DATA_ADDR7 = (`REGFILE_PATH.Registers[9]  + IMM2[11:0]);
        DATA_ADDR8 = (`REGFILE_PATH.Registers[10] + IMM3[11:0]);

        `IMEM_PATH.memory[INST_ADDR + 0] = {IMM0[11:5], 5'd1, 5'd2,  `FNC_SW, IMM0[4:0], `OPC_STORE};

        `DMEM_PATH.memory[DATA_ADDR0>>2] = 0; // <----------------------------------------------- CHANGED

        reset_cpu();

        check_result_dmem(DATA_ADDR0>>2, 32'h12345678, "S-Type SW"); // <----------------------------------------------- CHANGED

        // Test U-Type Insts --------------------------------------------------
        // - LUI
        reset();

        IMM       = 32'h7FFF_0123;
        INST_ADDR = 14'h0000;

        `IMEM_PATH.memory[INST_ADDR + 0] = {IMM[31:12], 5'd3, `OPC_LUI};

        reset_cpu();

        check_result_rf(3,  32'h7fff0000, "U-Type LUI");

        // Test J-Type Insts --------------------------------------------------
        // - JAL
        reset();

        `REGFILE_PATH.Registers[1] = 100;
        `REGFILE_PATH.Registers[2] = 200;
        `REGFILE_PATH.Registers[3] = 300;
        `REGFILE_PATH.Registers[4] = 400;

        IMM       = 32'h0000_0FF0;
        INST_ADDR = 14'h0000;
        JUMP_ADDR = (32'h1000_0000 + {IMM[20:1], 1'b0}) >> 2;

        `IMEM_PATH.memory[INST_ADDR + 0]   = {IMM[20], IMM[10:1], IMM[11], IMM[19:12], 5'd5, `OPC_JAL};
        `IMEM_PATH.memory[INST_ADDR + 1]   = {`FNC7_0, 5'd2, 5'd1, `FNC_ADD_SUB, 5'd6, `OPC_ARI_RTYPE};
        `IMEM_PATH.memory[JUMP_ADDR[13:0]] = {`FNC7_0, 5'd4, 5'd3, `FNC_ADD_SUB, 5'd7, `OPC_ARI_RTYPE};

        reset_cpu();

        check_result_rf(5'd5, 32'h0000_0004, "J-Type JAL");  // <----------------------------------------------- CHANGED
        check_result_rf(5'd7, 700, "J-Type JAL");
        check_result_rf(5'd6, 0, "J-Type JAL");


        // Test B-Type Insts --------------------------------------------------
        // - BEQ, BNE

        #100;
        IMM       = 32'h0000_0FF0;
        INST_ADDR = 14'h0000;
        JUMP_ADDR = (32'h0000ff0) >> 2;

        BR_TYPE[0]     = `FNC_BEQ;
        BR_NAME_TK1[0] = "B-Type BEQ Taken 1";
        BR_NAME_TK2[0] = "B-Type BEQ Taken 2";
        BR_NAME_NTK[0] = "B-Type BEQ Not Taken";

        BR_TAKEN_OP1[0]  = 100; 
        BR_TAKEN_OP2[0]  = 100;
        BR_NTAKEN_OP1[0] = 100; 
        BR_NTAKEN_OP2[0] = 200;

        BR_TYPE[1]       = `FNC_BNE;
        BR_NAME_TK1[1]   = "B-Type BNE Taken 1";
        BR_NAME_TK2[1]   = "B-Type BNE Taken 2";
        BR_NAME_NTK[1]   = "B-Type BNE Not Taken";
        BR_TAKEN_OP1[1]  = 100; BR_TAKEN_OP2[1]  = 200;
        BR_NTAKEN_OP1[1] = 100; BR_NTAKEN_OP2[1] = 200;


        reset();
        `REGFILE_PATH.Registers[1] = BR_TAKEN_OP1[0];
        `REGFILE_PATH.Registers[2] = BR_TAKEN_OP2[0];
        `REGFILE_PATH.Registers[3] = 300;
        `REGFILE_PATH.Registers[4] = 400;

        // Test branch taken
        `IMEM_PATH.memory[INST_ADDR + 0]   = {IMM[12], IMM[10:5], 5'd2, 5'd1, BR_TYPE[0], IMM[4:1], IMM[11], `OPC_BRANCH};
        `IMEM_PATH.memory[INST_ADDR + 1]   = {`FNC7_0, 5'd4, 5'd3, `FNC_ADD_SUB, 5'd5, `OPC_ARI_RTYPE};
        `IMEM_PATH.memory[JUMP_ADDR] = {`FNC7_0, 5'd4, 5'd3, `FNC_ADD_SUB, 5'd6, `OPC_ARI_RTYPE};

        reset_cpu();

        check_result_rf(5'd5, 0,   BR_NAME_TK1[0]);
        check_result_rf(5'd6, 700, BR_NAME_TK2[0]);

        reset();

        `REGFILE_PATH.Registers[1] = BR_NTAKEN_OP1[1];
        `REGFILE_PATH.Registers[2] = BR_NTAKEN_OP2[1];
        `REGFILE_PATH.Registers[3] = 300;
        `REGFILE_PATH.Registers[4] = 400;

        // Test branch not taken
        `IMEM_PATH.memory[INST_ADDR + 0] = {IMM[12], IMM[10:5], 5'd2, 5'd1, BR_TYPE[0], IMM[4:1], IMM[11], `OPC_BRANCH};
        `IMEM_PATH.memory[INST_ADDR + 1] = {`FNC7_0, 5'd4, 5'd3, `FNC_ADD_SUB, 5'd5, `OPC_ARI_RTYPE};

        reset_cpu();
        check_result_rf(5'd5, 700, BR_NAME_NTK[0]);

        // ... what else?
        all_tests_passed = 1'b1;

        repeat (100) @(posedge clk);
        $display("All tests passed!");
        $finish();
    end

endmodule
