`timescale 1ns/1ns

`include "../include/opcode.vh"
`include "../include/mem_path.vh"

// This testbench tests if the cpu module can decode and execute
// all the instructions specified in the spec (RV32I).
// Some tests for data hazards and control hazards are also included.

// How does the testbench work?
// For each test, the testbench initializes IMem with one or several instructions
// (encoded in binary format as specified in the spec) for testing.
// RegFile and DMem are also initialized with some data.
// Then, the clock is advanced until the cpu module gives correct result
// in the RegFile or DMem. If no correct result is returned after a "timeout" cycle,
// the testbench will be terminated (or failed)

// This setting is different from other testbenches, in which the BIOSMem or IMem is initialized
// with a hex file generated by compiling the assembly/C code of the corresponding
// test software (the hex file contains the binary encoding of the instructions and data
// of the program). Here, we manually generate the instructions and data.

// Don't just run the testbench, look at the tests, see what they do.
// The testbench is intended to provide you some examples to get started.
// Feel free to make your own change.
// Note that the testbench is by no means exhaustive.
// You should add your own tests if there are cases you think the testbench
// does not cover.
// The testbench does not cover reading from BIOS memory

//ONLY THESE INSTRCUTIONS WILL BE TESTED 
//R type: add, sub, or, and, xor, sll, srl 
//I type: addi,  ori, andi, xori, slli, srli, lw
//S type: sw
//B type: beq, bne
//J type: jal
//U type: lui

module cep_tb();
    reg clk, rst;                          //TODO: ENSURE clk AND rst ARE SPELLED THE SAME
    parameter CPU_CLOCK_PERIOD = 20;

    reg [ 31:0] cycle;
    reg         done;
    reg [ 31:0] current_test_id = 0;
    reg [255:0] current_test_type;
    reg [ 31:0] current_output;
    reg [ 31:0] current_result;
    reg         all_tests_passed = 0;

    reg [  4:0] RD, RS1, RS2;
    reg [ 31:0] RD1, RD2;
    reg [  4:0] SHAMT;
    reg [ 31:0] IMM, IMM0, IMM1, IMM2, IMM3;
    reg [ 14:0] INST_ADDR;
    reg [ 14:0] DATA_ADDR;
    reg [ 14:0] DATA_ADDR0, DATA_ADDR1, DATA_ADDR2, DATA_ADDR3;
    reg [ 14:0] DATA_ADDR4, DATA_ADDR5, DATA_ADDR6, DATA_ADDR7;
    reg [ 14:0] DATA_ADDR8, DATA_ADDR9;
    reg [ 31:0] JUMP_ADDR;
    reg [ 31:0] BR_TAKEN_OP1  [5:0];
    reg [ 31:0] BR_TAKEN_OP2  [5:0];
    reg [ 31:0] BR_NTAKEN_OP1 [5:0];
    reg [ 31:0] BR_NTAKEN_OP2 [5:0];
    reg [  2:0] BR_TYPE       [5:0];
    reg [255:0] BR_NAME_TK1   [5:0];
    reg [255:0] BR_NAME_TK2   [5:0];
    reg [255:0] BR_NAME_NTK   [5:0];

    //CLK Generation
    initial clk = 0;
    always #(CPU_CLOCK_PERIOD/2) clk = ~clk;

    //TODO: Top module instantiation. CHANGE IF REQUIRED
    single_cycle cpu ( .clk (clk),
              .rst (rst) );

    wire [31:0] timeout_cycle = 10;

    //TODO: ENSURE REGISTERS OF REGFILE ARE NAMED AS'Registers' 
    //TODO: INSTRUCTION MEMORY IS NAMED AS 'memory'
    //TODO: DATA MEMORY IS NAMED AS 'memory' 
    //TODO: OTHERWISE CHANGE ALL OCCURENCES THROUGHOUT THE TESTBENCH
    //Reset IMem, DMem, and RegFile before running new test
    task reset;
        integer i;
        begin
        for (i = 0; i < 32; i = i + 1) begin
            `REGFILE_PATH.Registers[i] = 0;
        end
        for (i = 0; i < 512; i = i + 1) begin
            `DMEM_PATH.memory[i] = 0;
        end
        for (i = 0; i < 16; i = i + 1) begin
            `IMEM_PATH.memory[i] = 0;
        end
        end
    endtask

    task reset_cpu;
    begin
        rst = 1;
        @(posedge clk);
        #30;
        rst = 0;
    end
    endtask

    task init_rf;
        begin
        for (int i = 1; i < 32; i = i + 1) begin
            `REGFILE_PATH.Registers[i] = 100 * i + 1;  
        end
        end
    endtask


    // Check for timeout
    // If a test does not return correct value in a given timeout cycle,
    // we terminate the testbench
    initial begin
        while (all_tests_passed === 0) begin
        @(posedge clk);

        if (cycle === timeout_cycle) begin
            $display("[Failed] Timeout at [%d] test %s, expected_result = %h, got = %h",
                    current_test_id, current_test_type, current_result, current_output);
            $finish();
        end

        end
    end

    always @(posedge clk) begin
        if (done === 0)
        cycle <= cycle + 1;
        else
        cycle <= 0;
    end

    // Check result of RegFile
    // If the write_back (destination) register has correct value (matches "result"), test passed
    // This is used to test instructions that update RegFile
    task check_result_rf;
        input [31:0]  rf_wa;
        input [31:0]  result;
        input [255:0] test_type;
        
        begin
            done = 0;
            current_test_id   = current_test_id + 1;
            current_test_type = test_type;
            current_result    = result;

            while (`REGFILE_PATH.Registers[rf_wa] !== result) begin     
                current_output = `REGFILE_PATH.Registers[rf_wa];
                @(negedge clk);
            end

            cycle = 0;
            done = 1;
            $display("[%d] Test %s passed!", current_test_id, test_type);
        end

    endtask

    // Check result of DMem
    // If the memory location of DMem has correct value (matches "result"), test passed
    // This is used to test store instructions
    task check_result_dmem;
        input [31:0]  addr;
        input [31:0]  result;
        input [255:0] test_type;

        begin
            done = 0;
            current_test_id   = current_test_id + 1;
            current_test_type = test_type;
            current_result    = result;

            while (`DMEM_PATH.memory[addr] !== result) begin   
                current_output = `DMEM_PATH.memory[addr];
                @(negedge clk);
            end

            cycle = 0;
            done = 1;
            $display("[%d] Test %s passed!", current_test_id, test_type);
        end

    endtask

    initial begin
        $dumpfile("dump.vcd");
        $dumpvars(0, cpu);
        rst = 0;

        // Reset the CPU
        rst = 1;
        repeat (1) @(posedge clk);

        @(negedge clk);
        rst = 0;
        // Test Custom Insts --------------------------------------------------
        // - BITREV
        
        // Test 1: Simple bit reversal (0x0000_000F -> 0xF000_0000)
        reset();
        RS1 = 1;
        RD  = 2;
        `REGFILE_PATH.Registers[RS1] = 32'h0000_000F;
        INST_ADDR = 14'h0000;

        `IMEM_PATH.memory[INST_ADDR + 0] = {`FNC7_BITREV, 5'd0, RS1, `FNC3_BITREV, RD, `OPC_CUSTOM_0};

        reset_cpu();
        check_result_rf(RD, 32'hF000_0000, "Custom BITREV Test 1");
        
        // Test Custom Insts --------------------------------------------------
        // - CABS
        
        // Test 1: CABS with a positive number (20 -> 20)
        reset();
        RS1 = 1;
        RD  = 2;
        `REGFILE_PATH.Registers[RS1] = 32'd20; 
        INST_ADDR = 14'h0000;

        // R-Type Pattern: {funct7, rs2(tied to 0), rs1, funct3, rd, opcode}
        `IMEM_PATH.memory[INST_ADDR + 0] = {`FNC7_CABS, 5'd0, RS1, 3'b000, RD, `OPC_CUSTOM_0};

        reset_cpu();
        check_result_rf(RD, 32'd20, "Custom CABS Test 1 (Positive)");


        // Test 2: CABS with a negative number (-500 -> 500)
        reset();
        RS1 = 3;
        RD  = 4;
        `REGFILE_PATH.Registers[RS1] = -500; // Stores as 32'hFFFFFE0C in two's complement
        INST_ADDR = 14'h0000;

        `IMEM_PATH.memory[INST_ADDR + 0] = {`FNC7_CABS, 5'd0, RS1, 3'b000, RD, `OPC_CUSTOM_0};

        reset_cpu();
        check_result_rf(RD, 32'd500, "Custom CABS Test 2 (Negative)");

        all_tests_passed = 1'b1;

        repeat (100) @(posedge clk);
        $display("All tests passed!");
        $finish();
    end

endmodule
