`timescale 1ns/1ps

module testbench;

    // Signals
    logic clk;
    logic rst;

    // Instantiate your CPU
    // (Ensure the module name and ports match your top-level RTL)
    single_cycle dut (
        .clk(clk),
        .rst(rst)
    );

    // Clock Generation (10ns period -> 100MHz)
    always #5 clk = ~clk;

    // Test Sequence
    initial begin
        $dumpfile("dump.vcd");
        $dumpvars(0, testbench);

        // 1. Load the Custom Compiled Hex File
        // Adjust the hierarchical path (`dut.instr_mem.memory`) to match your exact RTL.
        // $readmemh("sw/program.hex", dut.instr_mem.memory);

        // 2. Inject Raw Sensor Data into Data Memory
        // Our assembly code reads from base address 0x1000. 
        // Because your memory uses word-indexing (addr[11:2]), 0x1000 / 4 = Index 1024.
        dut.d_mem.memory[1024] = 32'hFFFFFE0C; // Sensor 1: -500 (Testing CABS)
        dut.d_mem.memory[1025] = 32'h00000020; // Sensor 2: 32   (Testing BITREV)
        dut.d_mem.memory[1026] = 32'hFFFFFFFF; // Sensor 3: -1   (Testing edge cases)

        // Initialize signals
        clk = 0;
        rst = 1;

        // Apply reset for one clock cycle
        #10;
        rst = 0;
        
        // 3. Wait for execution
        // The program loops 3 times and hits an infinite trap. 5000ns is plenty of time.
        #5000;

        // 4. Evaluate the Results in the Network Buffer
        // Our assembly code writes the output to base address 0x2000.
        // 0x2000 / 4 = Index 2048.
        $display("\n====================================================");
        $display("          TELEMETRY SCRAMBLER RESULTS               ");
        $display("====================================================");
        
        // Index 2048: The Header (Generated by MASKI and BSWAP)
        $display("Header      (Mem[2048]) : %08x", dut.d_mem.memory[2048]);
        
        // Indices 2049-2051: The Scrambled Payloads (Generated by CABS, BITREV, SW.BSWAP)
        $display("Scrambled 1 (Mem[2049]) : %08x", dut.d_mem.memory[2049]);
        $display("Scrambled 2 (Mem[2050]) : %08x", dut.d_mem.memory[2050]);
        $display("Scrambled 3 (Mem[2051]) : %08x", dut.d_mem.memory[2051]);
        $display("====================================================\n");

        // End simulation
        $finish;
    end

endmodule